# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        mkdir binaries
        DOCKER_BUILDKIT=1 docker build --output binaries .
        
    - name: Upload tag version for artifactory
      uses: actions/upload-artifact@v4
      with:
        name: ssl_handshake
        path: binaries
        if-no-files-found: error

  # release:
  #   runs-on: ubuntu-latest
  #   steps:
    - name: Creates a release in GitHub and uploads attachments
      run: |
        gh release create v1.2.3 ssl_handshake
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
